### ISSUE TITLE
Install extension feature

### ISSUE THREAD

**Issue by TsuyoshiUshio** [microsoft/terraform-provider-azuredevops#135] opened 2019-10-21 20:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm wondering if there is a plan for installing extensions from the market place (or self build one).  When I wrote a provision script of Azure DevOps, it was required and compromised that we use pre provisioned org. However, install extensions might be a good feature for the initial setup of the Azure DevOps. 

### New or Affected Resource(s)

* azuredevops_ extensionmanagement or 
* azuredevops_extension

### Potential Terraform Configuration

Need to discuss however, something like this.

```hcl

resource "azuredevops_extension" "extension" {
  publisher_name = "publisher name"
  extension_name = "extension name"
}

```

### References

* [Installed Extensions - Install Extension By Name](https://docs.microsoft.com/en-us/rest/api/azure/devops/extensionmanagement/installed%20extensions/install%20extension%20by%20name?view=azure-devops-rest-5.1)

**Comment by nmiodice** [comment] 2019-10-22 15:53
@TsuyoshiUshio I agree! I like this item in our backlog. Would be great to see this feature after we foll out the milestone 1 features!

**Comment by nmiodice** [comment] 2020-05-29 20:21
Duplicate of https://github.com/microsoft/terraform-provider-azuredevops/issues/197

**Closed by nmiodice** 2020-05-29 20:21 UTC
Labels: priority-low
