### ISSUE TITLE
Issue removing group membership

### ISSUE THREAD

**Issue by xibix-fp** [microsoft/terraform-provider-azuredevops#188] opened 2019-11-06 14:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v0.12.12
+ provider.azuread v0.6.0
+ provider.azuredevops v0.0.1
+ provider.azurerm v1.36.1
+ provider.kubernetes v1.9.0
+ provider.random v2.2.1

### Affected Resource(s)

* azuredevops_group_membership

### Terraform Configuration Files

```hcl
resource "azuredevops_project" "shared" {
  project_name       = "${var.prefix}.${terraform.workspace}"
  description        = "Azure DevOps Project for ${terraform.workspace}"
  visibility         = "private"
  version_control    = "Git"
}

data "azuredevops_group" "shared" {
  project_id = "${azuredevops_project.shared.id}"
  name       = "Project Administrators"
}

resource "azuredevops_user_entitlement" "shared" {
  principal_name = "${var.project_admins[count.index]}"
  count          = "${length(var.project_admins)}"
  origin         = "aad"
}

resource "azuredevops_group_membership" "shared" {
  group   = "${data.azuredevops_group.shared.descriptor}"
  members = "${azuredevops_user_entitlement.shared.*.descriptor}"
}

variable "project_admins" {
  description = "A list of AAD user emails that will be granted access to the provisioned project."
  type        = "list"
  default = ["user1@xyz.onmicrosoft.com", "user2@xyz.onmicrosoft.com"]
}
```

### Debug Output

azuredevops_user_entitlement.shared[1]: Destroying... [id=0b6df687-cc1c-686e-857f-dcf816a7ab84]
azuredevops_user_entitlement.shared[1]: Destruction complete after 2s
azuredevops_group_membership.shared: Modifying... [id=5577006791947779410]

Error: rpc error: code = Unavailable desc = transport is closing

### Expected Behavior

It should be possible to modify the list memberships for a project in Azure DevOps. For example removing a user.

### Actual Behavior

A project with one or two user memberships can be created successful. If reapply the template, the output from above occurs (Error: rpc error: code = Unavailable desc = transport is closing)

### Steps to Reproduce

1. `terraform apply`
2. Remove one entry from the variable project_administrators
3.`terraform apply`
4. RPC error occurs

### Important Factoids

none

### References

none

**Comment by mikaelkrief** [comment] 2019-11-20 16:18
@nmiodice I am interressed to investigate and fix this

**Comment by nmiodice** [comment] 2019-11-20 17:05
@mikaelkrief assigned. you may want to validate this bug before spending much time on it. Also we have a test that is currently not being used due to the fact that we see it cause transient issues due to a data propagation delay within AzDO related to group memberships.

See more info here: https://github.com/microsoft/terraform-provider-azuredevops/issues/174

**Comment by mikaelkrief** [comment] 2019-11-25 10:12
@nmiodice I reproducted this issue, by adding new user in the group

**Comment by nmiodice** [comment] 2019-12-12 23:00
Fixed in https://github.com/microsoft/terraform-provider-azuredevops/pull/212

**Closed by nmiodice** 2019-12-12 23:00 UTC
Labels: bug
