### ISSUE TITLE
Increasing transient build failures in CI pipeline

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#354] opened 2020-06-01 22:40 UTC
There is an increase in failures in the CI pipeline that need to be investigated. Otherwise, development against this provider is increasingly difficult and OSS contributors will loose their patience when contributing, especially since they cannot see the build logs

Example failures:
```
2020-06-01T22:34:03.6100344Z --- FAIL: TestAccAzureDevOpsProject_DataSource (23.99s)
2020-06-01T22:34:03.6100846Z     testing.go:654: Step 1 error: errors during apply:
2020-06-01T22:34:03.6101113Z         
2020-06-01T22:34:03.6101869Z         Error: Error deleting project: VS402392: Project operation may not be performed due to ongoing work for the team project 'test"acc"dq74p8rcd7'. Wait a few minutes and try again.
2020-06-01T22:34:03.6102344Z         
2020-06-01T22:34:03.6102509Z         
```

There may be a use case to leverage the Terraform [Retry](https://www.terraform.io/docs/extend/resources/retries-and-customizable-timeouts.html#retry) feature on project operations.

**Comment by nmiodice** [comment] 2020-06-01 22:41
cc @xuzhang3

**Comment by EliiseS** [comment] 2020-06-01 22:43
```bash
--- FAIL: TestAccAzureDevOpsProject_DataSource (23.99s)
    testing.go:654: Step 1 error: errors during apply:
        
        Error: Error deleting project: VS402392: Project operation may not be performed due to ongoing work for the team project 'test"acc"dq74p8rcd7'. Wait a few minutes and try again.
```

https://dev.azure.com/terraform-azdo/terraform-provider-azuredevops/_build/results?buildId=1104&view=logs&j=b08f2e40-82fb-586f-1049-b3a2527363c9&t=a6782e9d-c568-5eeb-da73-1de6887d27cb

**Comment by xuzhang3** [comment] 2020-06-02 09:39
Not sure what caused this problem,  guess it was caused by parallel operations on the same project. Need more investigation.

**Comment by tmeckel** [comment] 2020-06-02 12:28
I'd like to cite my statements about data sources and resources in Terraform and what implementation requirements they have.

https://github.com/microsoft/terraform-provider-azuredevops/pull/292#issuecomment-637467698

**Comment by nmiodice** [comment] 2020-06-03 01:37
Another one:
https://dev.azure.com/terraform-azdo/terraform-provider-azuredevops/_build/results?buildId=1129&view=logs&j=b08f2e40-82fb-586f-1049-b3a2527363c9&t=a6782e9d-c568-5eeb-da73-1de6887d27cb
```
2020-06-02T22:38:00.0465328Z --- FAIL: TestAccProject_CreateAndUpdate (26.29s)
2020-06-02T22:38:00.0465631Z     testing.go:654: Step 1 error: errors during apply:
2020-06-02T22:38:00.0465880Z         
2020-06-02T22:38:00.0466557Z         Error: Error updating project: VS402392: Project operation may not be performed due to ongoing work for the team project 'test"acc"e0zdk8htyg'. Wait a few minutes and try again.
2020-06-02T22:38:00.0466981Z         
2020-06-02T22:38:00.0467342Z           on /tmp/tf-test251961732/main.tf line 2:
2020-06-02T22:38:00.0467785Z           (source code not available)
2020-06-02T22:38:00.0468004Z         
2020-06-02T22:38:00.0468161Z         
```

**Comment by nmiodice** [comment] 2020-06-03 21:22
> I'd like to cite my statements about data sources and resources in Terraform and what implementation requirements they have.
> 
> [#292 (comment)](https://github.com/microsoft/terraform-provider-azuredevops/pull/292#issuecomment-637467698)

See #360 and #361

**Comment by xuzhang3** [comment] 2020-06-05 07:30
I will close this issue as the retry logic for project create and update has been added in PR #362 .

**Closed by xuzhang3** 2020-06-05 07:30 UTC
Labels: bug, investigation
