### ISSUE TITLE
Support Bearer Token

### ISSUE THREAD

**Issue by richardgavel** [microsoft/terraform-provider-azuredevops#351] opened 2021-04-02 17:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have an Azure DevOps pipeline who's job it is to run the Terraform to configure Azure DevOps. However, we'd like to take the AccessToken provided as $(System.AcessToken) to run it, rather than providing a hard coded PAT. However, that token is not a PAT, it's a bearer token, which requires different configuration of the provider. We are able to make use of the bearer token in using the VSTeam powershell library within an ADO pipeline.

https://github.com/MethodsAndPractices/vsteam/blob/trunk/.docs/Set-VSTeamAccount.md#example-7

### Potential Terraform Configuration

```hcl
provider azuredevops {
  org_service_url       = ...
  bearer_token          = ...
}
```

* #0000

**Comment by xuzhang3** [comment] 2021-04-07 07:51
hi @richardgavel  SDK does not support bearer token. If we need support bearer token, ADO should create new connection to support  the new HTTP headers.
https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops#authorize-your-app

**Comment by tmeckel** [comment] 2021-07-25 18:37
Duplicate of https://github.com/microsoft/terraform-provider-azuredevops/issues/419

**Comment by xuzhang3** [comment] 2021-08-02 02:10
Duplicate of #419 ,  close this issue.

**Closed as completed by xuzhang3** 2021-08-02 02:10 UTC
Labels: enhancement
