### ISSUE TITLE
Issue to create a group under project using azuredevops_group

### ISSUE THREAD

**Issue by kur4mot0** [microsoft/terraform-provider-azuredevops#558] opened 2022-03-10 14:47 UTC
Using the following example: https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/group

Setting the scope on resource azuredevops_group doesn't make any difference. The group still being create on organization level instead on project level. 

I used the same code, the group was created under organization level.

Terraform v1.1.7
on windows_386
+ provider registry.terraform.io/microsoft/azuredevops v0.2.0

**Comment by rvdginste** [comment] 2022-03-10 20:26
I noticed the same and it seems to be a regression: it is working correctly on version 0.1.8 of the azuredevops provider.

**Comment by xuzhang3** [comment] 2022-03-11 06:22
#559  will downgrade the API to v5 which will fix this bug

**Comment by kur4mot0** [comment] 2022-03-11 07:09
> I noticed the same and it seems to be a regression: it is working correctly on version 0.1.8 of the azuredevops provider.

After I have created the issue, I did the downgrade and worked like a charm.

**Comment by MBarendregt** [comment] 2022-03-23 15:23
Will this also be released soon? Noticed you made the fix @xuzhang3. Thanks!

**Comment by xuzhang3** [comment] 2022-03-24 07:50
@MBarendregt  Working on it, I cannot give you timeline for now,  will coming soon.

**Comment by avishnyakov** [comment] 2022-04-01 03:21
Confirming the same:
* regression on 0.2.0
* scope is being ignored
* downgrade to 0.1.8 works well

**Comment by xuzhang3** [comment] 2022-04-19 09:05
Fixed in v0.2.1

**Closed as completed by xuzhang3** 2022-04-19 09:05 UTC
Labels: bug
