### ISSUE TITLE
can't destroy with nested providers

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/terraform-provider-azuredevops#364] opened 2021-04-22 12:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.56.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.3

$ terraform providers
Providers required by configuration:
.
└── module.service_principal
    ├── provider[registry.terraform.io/microsoft/azuredevops] >= 0.1.3
    ├── provider[registry.terraform.io/hashicorp/azurerm] >= 2.55.0
    ├── provider[registry.terraform.io/hashicorp/azuread]
    ├── provider[registry.terraform.io/hashicorp/random]
    └── provider[registry.terraform.io/hashicorp/time]

### Affected Resource(s)

* `provider "azuredevops"`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}

provider "azuredevops" {
  org_service_url = var.org_service_url
  # personal_access_token = var.personal_access_token
}

resource "azuredevops_serviceendpoint_azurerm" "azuredevops_serviceendpoint_azurerm" {
  for_each = data.azuredevops_project.azuredevops_projects

  project_id                = each.value.id
  service_endpoint_name     = "se"
  azurerm_spn_tenantid      = data.azurerm_client_config.azurerm_client_config.tenant_id
  azurerm_subscription_id   = data.azurerm_client_config.azurerm_client_config.subscription_id
  azurerm_subscription_name = data.azurerm_subscription.azurerm_subscription.display_name

  credentials {
    serviceprincipalid  = azuread_service_principal.azuread_service_principal.application_id
    serviceprincipalkey = azuread_service_principal_password.azuread_service_principal_password.value
  }
}
```

### Debug Output

```hcl
$ terraform destroy -parallelism=300
Acquiring state lock. This may take a few moments...
module.service_principal.azuredevops_resource_authorization.azuredevops_resource_authorization["devops"]: Refreshing state... [id=xxx]
module.service_principal.azuredevops_serviceendpoint_azurerm.azuredevops_serviceendpoint_azurerm["devops"]: Refreshing state... [id=xxx]
╷
│ Error: the url of the Azure DevOps is required
│
│   on .terraform/modules/service_principal/providers.tf line 11, in provider "azuredevops":
│   11: provider "azuredevops" {
```

### Expected Behavior

to be able to destroy the resources

### Actual Behavior

`│ Error: the url of the Azure DevOps is required`

### Steps to Reproduce

1. `erraform destroy `

### Important Factoids

provider is in a nested module

**Comment by xuzhang3** [comment] 2021-05-07 06:49
Hi @FernandoMiguel  Can you share your module construct and TF files? With this limited information, I cannot reproduce this error. If you want share the variables though different module, you may need more configuration, otherwise the module cannot read the defined configurations.
Ref Terraform post: https://discuss.hashicorp.com/t/codependent-values-across-different-modules/11455

**Comment by FernandoMiguel** [comment] 2021-05-07 07:39
I'm off work today.
But I'll try to build you a sample reproduce. 
But basically all it takes is to place the provider inside the module, not in the root module

**Comment by dmccaffery** [comment] 2021-07-26 13:31
You cannot put providers inside of a module -- removing the reference to the module also removes the provider block which means the provider is no longer available to perform the destroy. This is true for all terraform providers and is not specific to the azuredevops provider.

Always include providers in root modules and declare the required providers in a terraform required_providers block within the module.

**Comment by xuzhang3** [comment] 2021-08-02 03:38
Close this issue, feel free to open another if you have questions.

**Closed as completed by xuzhang3** 2021-08-02 03:38 UTC
Labels: help wanted, waiting-response
