### ISSUE TITLE
azuredevops_git_repository "Import" does not import from another Git repository

### ISSUE THREAD

**Issue by fyvekatz** [microsoft/terraform-provider-azuredevops#325] opened 2021-03-12 21:36 UTC
I've been unable to create a repo that successfully imports the content of another (public) repo. I can provide logs if necessary but the scenario is simple. Using the following main.tf, a project is created in my instance of Azure DevOps. A properly named repo is created a long with it, but it is not populated with the contents from the public remote repository.

From the logs, the version of the azuredevops provider that was installed during `terraform init`.

`- Installed microsoft/azuredevops v0.1.2`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.51.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.2


Your version of Terraform is out of date! The latest version
is 0.14.8. You can update by downloading from https://www.terraform.io/downloads.html

```
### Affected Resource(s)

* `azuredevops_git_repository`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuredevops = {
      source = "microsoft/azuredevops"
    }
  }
}

provider "azuredevops" {
  org_service_url       = var.azdo_org_url
  personal_access_token = var.azdo_personal_access_token
}

resource "azuredevops_project" "project" {
  name                = "Test Demo"
  visibility          = "private"

  features = {
    "boards" = "enabled"
  }
}

resource "azuredevops_git_repository" "repo" {
  project_id           = azuredevops_project.project.id
  name                 = "Test Repo"

  # At the moment, this doesn't work. Investigating.

  initialization {
    init_type 	= "Import"
    source_type = "Git"
    source_url 	= "https://github.com/WebGoat/WebGoat"
  }
}
```

### Debug Output

https://gist.github.com/fyvekatz/038bb10ea7471a62f2186187752d07dc

### Panic Output

None.

### Expected Behavior

Project and repo should have been created and the repo populated with the contents of https://github.com/WebGoat/WebGoat

### Actual Behavior

Project and Repo were created but the repo was uninitialized.

### Steps to Reproduce

1. Provide your own org url and access token to the provider section of main.tf.
2. `terraform init`
3. `terraform apply`

### Important Factoids

No.

### References

* #0000

**Comment by xuzhang3** [comment] 2021-03-15 03:31
Hi @fyvekatz  I cannot reproduce your error.  You can find all the repos at `Project settings -> Repos -> Repositories`.
Azure DevOps will create a default repo with same name with project, so project `Test Demo` have two repo.
![image](https://user-images.githubusercontent.com/57888764/111100038-ca863300-8581-11eb-8911-3d810a42799f.png)

**Comment by xuzhang3** [comment] 2021-05-11 09:31
@fyvekatz  DevOps will create a default repo have the same name as the project and this repo will displayed as the default repo, you can find all the repos at: `Project settings -> Repos -> Repositories`

**Comment by alexott** [comment] 2021-06-17 09:17
just for update - Import works just fine in 0.1.5

**Comment by xuzhang3** [comment] 2021-07-20 03:06
Close this issue, feel free to open another issue if you have questions.

**Closed as completed by xuzhang3** 2021-07-20 03:06 UTC
Labels: question, waiting-response
