### ISSUE TITLE
Provider produced inconsistent result after apply for azuredevops_resource_authorization

### ISSUE THREAD

**Issue by lightnir** [microsoft/terraform-provider-azuredevops#145] opened 2020-08-11 21:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v0.12.29
+ provider.azuredevops v0.0.1
+ provider.azurerm v2.22.0

### Affected Resource(s)

* `azuredevops_resource_authorization`

### Terraform Configuration Files

```hcl
locals {
  subscription_name     = "My Subscription"
  project_name          = "My project"
  service_endpoint_name = "Terraform Service Connection (AzureRM)"
  description           = "This is a service connection created by Terraform"
}

provider "azuredevops" {
  version  = ">= 0.0.1"
}

provider "azurerm" {
  version = "~> 2.22"
  features {}
}

data "azurerm_client_config" "current" {}

data "azuredevops_project" "p" {
  project_name = local.project_name
}

resource "azuredevops_serviceendpoint_azurerm" "main" {
  project_id                = data.azuredevops_project.p.id
  service_endpoint_name     = local.service_endpoint_name
  description               = local.description
  azurerm_spn_tenantid      = data.azurerm_client_config.current.tenant_id
  azurerm_subscription_id   = data.azurerm_client_config.current.subscription_id
  azurerm_subscription_name = local.subscription_name
}

resource "azuredevops_resource_authorization" "main" {
  project_id  = data.azuredevops_project.p.id
  resource_id = azuredevops_serviceendpoint_azurerm.main.id
  authorized  = true
  type        = "endpoint"
}
```

### Debug Output
```
2020/08/11 22:31:25 [DEBUG] azuredevops_serviceendpoint_azurerm.main: applying the planned Create change
2020-08-11T22:31:25.013+0200 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 2020/08/11 22:31:25 [DEBUG] setting computed for "authorization" from ComputedKeys
2020/08/11 22:31:25 [DEBUG] azuredevops_resource_authorization.main: applying the planned Create change
2020/08/11 22:31:25 [DEBUG] azuredevops_resource_authorization.main: apply errored, but we're indicating that via the Error pointer rather than returning it: Provider produced inconsistent result after apply: When applying changes to azuredevops_resource_authorization.main, provider "registry.terraform.io/-/azuredevops" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2020/08/11 22:31:25 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Provider produced inconsistent result after apply: When applying changes to azuredevops_resource_authorization.main, provider "registry.terraform.io/-/azuredevops" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2020/08/11 22:31:25 [ERROR] <root>: eval: *terraform.EvalSequence, err: Provider produced inconsistent result after apply: When applying changes to azuredevops_resource_authorization.main, provider "registry.terraform.io/-/azuredevops" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2020-08-11T22:31:25.910+0200 [DEBUG] plugin: plugin process exited: path=/Users/dawidj/projects/tf-azuredevops/auth_error_debug/.terraform/plugins/darwin_amd64/terraform-provider-azuredevops_v0.0.1_x4 pid=64715
2020-08-11T22:31:25.910+0200 [DEBUG] plugin: plugin exited
```

### Panic Output

N/A

### Expected Behavior

Terraform should create an AzureRM service connection and grant access permission to use in all pipelines.

### Actual Behavior

`terraform plan` shows that it will add 2 resources.
The first run of `terraform apply` fails to create azuredevops_resource_authorization resource.

```
➜ terraform apply -auto-approve
data.azuredevops_project.p: Refreshing state...
data.azurerm_client_config.current: Refreshing state...
azuredevops_serviceendpoint_azurerm.main: Creating...
azuredevops_serviceendpoint_azurerm.main: Creation complete after 1s [id=cf5de689-9080-4fa3-bdd1-bfb7c9619b45]
azuredevops_resource_authorization.main: Creating...

Error: Provider produced inconsistent result after apply

When applying changes to azuredevops_resource_authorization.main, provider
"registry.terraform.io/-/azuredevops" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
Running `terraform apply` a second time creates the resource authorization.

```
➜ terraform apply -auto-approve
data.azuredevops_project.p: Refreshing state...
data.azurerm_client_config.current: Refreshing state...
azuredevops_serviceendpoint_azurerm.main: Refreshing state... [id=d6b5693a-bf4c-4cbc-8394-f9c1dc377c61]
azuredevops_resource_authorization.main: Creating...
azuredevops_resource_authorization.main: Creation complete after 0s [id=d6b5693a-bf4c-4cbc-8394-f9c1dc377c61]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

* #0000

**Comment by xuzhang3** [comment] 2020-08-12 05:29
Hi @lightnir   You need add the  the service principal secret key and ID for `azuredevops_serviceendpoint_azurerm`,   see the `credentials ` block.
Example:
```
data "azuredevops_project" "p" {
  project_name = local.project_name
}

resource "azuredevops_serviceendpoint_azurerm" "main" {
  project_id                = data.azuredevops_project.p.id
  service_endpoint_name     = "MyAzureRM"
  description               = "Manege by Terraform"
  azurerm_spn_tenantid      = "xxxxxxxxxxxxxxxx"
  azurerm_subscription_id   = "xxxxxxxxxxxxxxxx"
  azurerm_subscription_name = "My sub"
  credentials {
    serviceprincipalid  = "xxxxxxxxxxxxxxx"
    serviceprincipalkey = "xxxxxxxxxxxxxxxx"
  }
}
```

**Comment by lightnir** [comment] 2020-08-12 15:55
Thanks, @xuzhang3 for the reply. I can confirm that by using the optional credential block this works. However, I want to use the Automatic AzureRM Service Endpoint where the service principal gets created automatically. As I stated above the problem isn't the Automatic vs Manual AzureRM Service Endpoint usage (second run of `terraform apply` on the automatic works fine), but rather something going wrong between calculating the plan and applying the changes.

I've increased the log level to TRACE and by looking at the log it seems that is the case.
```
2020/08/12 17:38:35 [TRACE] vertex "azuredevops_serviceendpoint_azurerm.main": visit complete
2020/08/12 17:38:35 [TRACE] dag/walk: visiting "azuredevops_resource_authorization.main"
2020/08/12 17:38:35 [TRACE] vertex "azuredevops_resource_authorization.main": starting visit (*terraform.NodeApplyableResourceInstance)
2020/08/12 17:38:35 [TRACE] vertex "azuredevops_resource_authorization.main": evaluating
2020/08/12 17:38:35 [TRACE] [walkApply] Entering eval tree: azuredevops_resource_authorization.main
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalSequence
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalGetProvider
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalReadDiff
2020/08/12 17:38:35 [TRACE] EvalReadDiff: Read Create change from plan for azuredevops_resource_authorization.main
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalIf
2020/08/12 17:38:35 [TRACE] <root>: eval: terraform.EvalNoop
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalIf
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalReadState
2020/08/12 17:38:35 [TRACE] EvalReadState: reading state for azuredevops_resource_authorization.main
2020/08/12 17:38:35 [TRACE] EvalReadState: no state present for azuredevops_resource_authorization.main
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalReadDiff
2020/08/12 17:38:35 [TRACE] EvalReadDiff: Read Create change from plan for azuredevops_resource_authorization.main
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalDiff
2020/08/12 17:38:35 [TRACE] Re-validating config for "azuredevops_resource_authorization.main"
2020/08/12 17:38:35 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2020/08/12 17:38:35 [TRACE] GRPCProvider: PlanResourceChange
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalCheckPlannedChange
2020/08/12 17:38:35 [TRACE] EvalCheckPlannedChange: Verifying that actual change (action Create) matches planned change (action Create)
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalGetProvider
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalReadState
2020/08/12 17:38:35 [TRACE] EvalReadState: reading state for azuredevops_resource_authorization.main
2020/08/12 17:38:35 [TRACE] EvalReadState: no state present for azuredevops_resource_authorization.main
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalReduceDiff
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalIf
2020/08/12 17:38:35 [TRACE] <root>: eval: terraform.EvalNoop
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalApplyPre
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalApply
2020/08/12 17:38:35 [DEBUG] azuredevops_resource_authorization.main: applying the planned Create change
2020/08/12 17:38:35 [TRACE] GRPCProvider: ApplyResourceChange
2020/08/12 17:38:35 [DEBUG] azuredevops_resource_authorization.main: apply errored, but we're indicating that via the Error pointer rather than returning it: Provider produced inconsistent result after apply: When applying changes to azuredevops_resource_authorization.main, provider "registry.terraform.io/-/azuredevops" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/08/12 17:38:35 [TRACE] EvalMaybeTainted: azuredevops_resource_authorization.main encountered an error during creation, so it is now marked as tainted
2020/08/12 17:38:35 [TRACE] <root>: eval: *terraform.EvalWriteState
```

**Comment by xuzhang3** [comment] 2020-08-13 08:12
Hi  @lightnir     this issue is strange. The service connection can be created but authorization operation won't success(service always returned with HTTP code 200, but authorization not added ). I have open a new issue in [DevOps authorization failed](https://developercommunity.visualstudio.com/content/problem/1148427/cannot-perform-authorization-operation-for-auzrerm.html)

**Comment by xuzhang3** [comment] 2020-09-21 09:16
@lightnir Looks like that service team have fixed this issue, I have tested and authorization works now.

**Comment by lightnir** [comment] 2020-09-23 15:20
@xuzhang3 Sorry for the late reply. I've run the same codebase (as in the initial post) form a clean start (removed .terraform folder and the tfstate file) and I'm still getting the same error. How did you test the authorization?

**Comment by xuzhang3** [comment] 2020-09-24 02:19
@lightnir  I just run the TF script you provide in this issue and the authorization is successful. A couple weeks ago, when I run the script, the authorization always failed though the HTTP response code is 200. Looks this issue still exist, I need to figure out how 
 to reproduce this issue first, maybe I need to add a retry logic for this scenario.

**Comment by xuzhang3** [comment] 2021-02-05 09:05
Close this issue. v0.1.2 has enhance the service connection state check during creation/deletion, the state handler will block the creation/delition until the service connection is ready or fail.

**Closed as completed by xuzhang3** 2021-02-05 09:05 UTC
Labels: question, waiting-response
